### ISSUE TITLE
Output folder creation when isSeasonalForecast = false

### ISSUE THREAD

**Issue by lroffia** [ARPA-SIMC/CRITERIA1D#1]
An error is raised if the output directory is not present and seasonal forecast disabled.

In Criteria1DProject.cpp, the following line (line 310):

QString outputDbPath = getFilePath(**outputCsvFileName**);

should be replaced with:

QString outputDbPath = getFilePath(**dbOutputName**);

Tested on MacOS. Following the INI file used:

[software]
software="CRITERIA1D"

[project]
path=""
name="kiwifruit"
db_meteo="./data/meteo_zattaglia.db"
#db_meteo=./data/DBGridXML_ERG5_v2.1.xml
#db_meteo=data/DBGridXML_ERG5_v1.xml
db_soil="./data/soil_ER_2002.db"
db_crop="./data/crop.db"
db_units="./data/units.db"
db_output="./output/kiwifruit.db"

[forecast]
isSeasonalForecast=false
isShortTermForecast=false

**Comment by ftomei** [comment]
Thanks Luca, fixed!
I add you as triage collaborator to the distribution

**Comment by lroffia** [comment]
Thank you!
