### ISSUE TITLE
Missing field in output DB

### ISSUE THREAD

**Issue by lroffia** [ARPA-SIMC/CRITERIA1D#2]
It seems like the field **RAW** is missing in the output DB. We are using the following to aggregate some outputs:

WC_PROFILE = WATER_CONTENT * ROOTDEPTH
DEFICIT_PROFILE = DEFICIT * ROOTDEPTH
THRESHOLD = WATER_CONTENT * ROOTDEPTH * **RAW**

Can (some of) these be replaced by other output fields? Has **RAW** be renamed?

Thank you.

**Comment by ftomei** [comment]
Hi Luca!
yes, RAW is new renamed READILY_AW
to better identify the three AW variables:
- AVAILABLE_WATER is all the water above the wilting point
- READILY_AW is the water readily available for the crop
- FRACTION_AW is the fraction of available water (0: wilting point, 1: field capacity, >1: above field capacity)
all the variables are computed in in the first meter of soil

**Comment by ftomei** [comment]
Edit: 
READILY_AW is computed on all the rooting depth (it can be lower or greater of a meter)
**Warning**
What is your variable THRESHOLD? It's not correct multiply water content and readily AW (both expressed in mm of water)

**Comment by lroffia** [comment]
Sorry, I made a mistake. The exact formula for THRESHOLD is:
THRESHOLD = WATER_CONTENT * ROOTDEPTH **-** READILY_AW

**Comment by ftomei** [comment]
Ok, this is correct, it returns a rough estimate of the minimum water content to avoid crop water stress

**Comment by lroffia** [comment]
Think you Faust!Inviato da smartphone Samsung Galaxy.
-------- Messaggio originale --------Da: Fausto Tomei <notifications@github.com> Data: 23/08/20  17:23  (GMT+01:00) A: ARPA-SIMC/CRITERIA1D <CRITERIA1D@noreply.github.com> Cc: Luca Roffia <lroffia@gmail.com>, Author <author@noreply.github.com> Oggetto: Re: [ARPA-SIMC/CRITERIA1D] Missing field in output DB (#2) 
Ok, this is correct, it returns a rough estimate of the minimum water content to avoid crop water stress

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ARPA-SIMC/CRITERIA1D/issues/2#issuecomment-678787290",
"url": "https://github.com/ARPA-SIMC/CRITERIA1D/issues/2#issuecomment-678787290",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
