### ISSUE TITLE
upload appImage

### ISSUE THREAD

**Issue by lauracosta** [ARPA-SIMC/CRITERIA1D#4]
Upload delle 6 appImage generate dal build ubuntu, come fatto per PRAGA.

**Comment by edigiacomo** [comment]
Se volete provare a creare un tag, vediamo se genera correttamente una release.

**Comment by lauracosta** [comment]
E' stata generata soltanto la CROP_EDITOR-x86_64.AppImage, dovrebbero essere 6 differenti. Scorrendo velocemente su travis ho il sospetto che si sovrascrivono, si ripete lo stesso nome: App name for filename: CROP_EDITOR

**Comment by edigiacomo** [comment]
Sì, anche secondo me ma non so perché linuxqtdeploy si comporti così. Ho forzato la ricreazione del tag, dopo aver messo un `set -x` in `deploy/build.sh` così forse ci rendiamo conto meglio di cosa succede https://travis-ci.org/github/ARPA-SIMC/CRITERIA1D/jobs/736008509

**Comment by edigiacomo** [comment]
Da https://travis-ci.org/github/ARPA-SIMC/CRITERIA1D/jobs/736008509#L4456

```
+ cp tools/csvToMeteoDb/release/CsvToMeteoDb deploy/appimage/usr/bin/CsvToMeteoDb

+ ./linuxqtdeploy --appimage-extract-and-run deploy/appimage/usr/share/applications/CsvToMeteoDb.desktop -qmake=/opt/qt512/bin/qmake -qmlimport=/opt/qt512/qml -appimage -always-overwrite

linuxdeployqt 6 (commit d41e234), build 723 built on 2020-07-30 06:25:46 UTC

Desktop file as first argument: "deploy/appimage/usr/share/applications/CsvToMeteoDb.desktop"

desktopExecEntry: "CsvToMeteoDb"

desktopIconEntry: "CsvToMeteoDb"

Found binary from desktop file: "/root/src/deploy/appimage/usr/bin/CsvToMeteoDb"

FHS-like mode with PREFIX, fhsPrefix: "/root/src/deploy/appimage/usr"

app-binary: "/root/src/deploy/appimage/usr/bin/CsvToMeteoDb"

appDirPath: "/root/src/deploy/appimage"

relativeBinPath: "usr/bin/CsvToMeteoDb"

Found icons from desktop file: ("/root/src/deploy/appimage/CsvToMeteoDb.png")

preExistingToplevelIcon: "/root/src/deploy/appimage/CsvToMeteoDb.png"

appimagetool, continuous build (commit 0880085), build 2133 built on 2020-07-09 12:25:52 UTC

/root/src/deploy/appimage/CROP_EDITOR.desktop: warning: value "CROP_EDITOR" for key "Comment" in group "Desktop Entry" looks redundant with value "CROP_EDITOR" of key "Name"

Name: CROP_EDITOR

Icon: CROP_EDITOR

Exec: CROP_EDITOR

Comment: CROP_EDITOR

Type: Application

Categories: Office;
```

Non ho capito per quale motivo, pur passandogli `deploy/appimage/usr/share/applications/CsvToMeteoDb.desktop`, il programma va a considerare `deploy/appimage/CROP_EDITOR.desktop`. Il fatto che i file `.desktop` siano ripetuti sia in `deploy/appimage/usr/share/applications/` che in `deploy/appimage/` è corretto?

**Comment by edigiacomo** [comment]
Ho provato ad eliminare i file `deploy/appimage/*.desktop`, vediamo se cambia qualcosa.

**Comment by lauracosta** [comment]
Si sono dei refusi, il path corretto è deploy/appimage/usr/share/applications/ . Ho notato che in CRITERIA_GEO.desktop mancava un _, vediamo ora se li fa tutti e 6 (prima si fermava a 4)

**Comment by ftomei** [comment]
Ora funzia, ha generato tutti i sei pacchetti
