### ISSUE TITLE
driver MYSQL

### ISSUE THREAD

**Issue by ftomei** [ARPA-SIMC/CRITERIA1D#5]
il pacchetto installato non trova il driver per mysql 
QSqlDatabase: QMYSQL driver not loaded
QSqlDatabase: available drivers: QSQLITE
Connection with database fail.

**Comment by edigiacomo** [comment]
@ftomei dovrei aver corretto, rifaccio il pacchetto e ti avviso quando puoi provare.

**Comment by edigiacomo** [comment]
Prova ora.

**Comment by ftomei** [comment]
Ottimo, funzia!
Chiudo la issue
Credo che la stessa cosa andrebbe fatta in praga
