### ISSUE TITLE
copia .png in usr\share\CRITERIA1D\images

### ISSUE THREAD

**Issue by lauracosta** [ARPA-SIMC/CRITERIA1D#6]
Affinchè crop_editor e soil_editor abbiano i png che gli servono, è necessario copiare in usr\share\CRITERIA1D\images
le immagini presenti nel repoitory al path CRITERIA1D\deploy\usr\share\CRITERIA1D\images

**Comment by edigiacomo** [comment]
Installata la release 3 di CRITERIA1D 1.0.0 sul server `otto.metarpa`. Vi chiedo di controllare che sia tutto ok.

**Comment by ftomei** [comment]
Tutto ok! Grazie
